apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace.name }}
data:
  APP_NAME: {{ .Values.configmap.APP_NAME }}
  ENVIRONMENT: {{ .Values.configmap.ENVIRONMENT }}
