apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace.name }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secret.DATABASE_URL }}
  API_KEY: {{ .Values.secret.API_KEY }}   
